### PR TITLE
Craft CMS 4 and DDEV upgrade

### PR DESCRIPTION
**Pull request by mgambella**
This pull request encompasses a broad upgrade of packages and workflow.

The following things have been done:

1) CraftCMS upgraded to version 4.5.3
2) Formie plugin upgraded to version  2.0.35
3) Tags plugin upgraded to version 2.0.0
4) New environment based on DDEV has been setup for both backend and frontend
5) README has been edited with new instructions 
6) Frontend node packages have been upgraded to latest version
7) The order of template and script in Vue components has been swapped to conform nowadays standards
8) The casing of Vue components has been changed to PascalCase
9) Formatters and Linters have been introduced

Important notes:

1) after the upgrade some forms are not working, so this code is not stable yet: maybe this should be merged in another branch other than master
2) some fields in the graphql queries have beed deleted because they were failing
3) the form fieldsDemo is failing
4) overall, more testing is warranted

### CODE REVIEW

**Comment by mgambella** [comment]
As an extra note, I have already converted all the Vue 3 components to Composition API: but, in order to not add too much changes, I decided to not include them in this pull request: I will be happy to include them in a successive one.

**Comment by engram-design** [comment]
This is a great start, thanks! I’ll take some time to review, particularly as you mention there are outstanding issues.

**Comment by plcdnl** [comment]
Hi, sorry for the inconvenience. Is there any update on this point? Unfortunately I'm having a bit of trouble getting it to work again. @mgambella if it is not a problem for you to also share the version with the composition api, in addition to being truly grateful towards you, I would be very happy to contribute to perhaps making it available to everyone

**Comment by engram-design** [comment]
I haven't really had the chance to properly get my head around this, as there's some big changes. I'm a tiny bit inclined to split this into DDEV and Vue 3 composition API for simplicity. I personally don't use DDEV, but I know it's the Craft-recommended environment.

I also use Options vs Composition API, for no other reason than it's what I'm used to, but I'm well aware this can put off users who want "modern" Vue code (the Options API isn't going anywhere).

I've also been thinking of getting a lean React example going, to having several frameworks - while more to maintain - might be a better resource.

**Comment by mgambella** [comment]
hello @plcdnl the version I shared in this pull request has already been built with Composition API. I neglected this project for a while, but I am going to resume it again soon. I would be great if you also could contribute.

**Comment by plcdnl** [comment]
Thank you, for sure!

**Comment by mgambella** [comment]
@plcdnl I just upgraded the Craft CMS and npm packages and I noticed that it is still using Options API... sorry about that..
I am going to convert those to Composition API, but I will be working on my repository at https://github.com/mgambella/formie-headless

**Pull request closed without merging**
